### ISSUE TITLE
function for creating recommendations 

### ISSUE THREAD

**Issue by patcharees** [miferroudjene/RACF#4]
Hi,
Thanks for the code. How can I use the code to get recommendations for each user for the next visit (in the future)?

**Comment by miferroudjene** [comment]
Hello, 
For future prediction, you have to use the `prediction(predMat, k)` function in the `util.py` python module (https://github.com/MayloIFERR/RACF/blob/main/NextBasketRecomSys/src/util.py) : 
```
def prediction(predMat, k):
    '''
    In :
      predMat : the predection matrix 
      {UWPop, UB-CF, IB-CF }with/out recency (@r)
    Out :
      score, pred : ndarray of shape =(n_users, k)
      retun the top-k score and predection matrix
    '''
```
That, after calculating the recommendation matrix, denoted as `predMat`, following the desired method. The implemented methods (User-Wise Popularity, Popularity-based Collaborative Filtering :  UP-CF and IP-CF   ) are provided in the `NextBasketRecFramework.py` python module (https://github.com/MayloIFERR/RACF/blob/main/NextBasketRecomSys/src/NextBasketRecFramework.py).

For better illustration of the code, please check the provided notebook : [RecencyAwareCF.ipynb] (https://github.com/MayloIFERR/RACF/blob/main/RecencyAwareCF.ipynb)

**Comment by patcharees** [comment]
Thanks for the answer. However the predMat is created by a part of dataset (df_train), can it be used directly for future prediction for all users?

**Comment by miferroudjene** [comment]
well, at this point you got two solutions :  **either** (1) you train your model (i.e., calculate the recommendation matrix) on the whole dataset , And then predict the future items for the all the users  **OR** (2) make sur that the items included in your **df_train** DataFrame covers all available item in all users' history, otherwise it will throw an "index mismatch error".

I suggest to you to go with the first one. For my case I add a parameter to train only on a part of dataset, that to limit the computation on my own machine.

**Comment by miferroudjene** [comment]
Do you have any more questions ? if no, @patcharees please feel free the close the issue.
